Greeting.create(message: 'Hello, world!')
Greeting.create(message: 'Hi there!')
Greeting.create(message: 'Greetings From Venezuela!')
Greeting.create(message: 'Live Long and Prosper!')
Greeting.create(message: 'How do you do?!')
